// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:fagaaro/features/auth/data/models/user_profile_model.dart';
import 'package:fagaaro/features/locations/data/models/geofence_location_model.dart';
import 'package:fagaaro/features/sync/data/models/sync_queue_item_model.dart';
import 'package:fagaaro/features/todos/data/models/todo_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(GeofenceLocationModelAdapter());
    registerAdapter(SyncQueueItemModelAdapter());
    registerAdapter(TodoModelAdapter());
    registerAdapter(UserProfileModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(GeofenceLocationModelAdapter());
    registerAdapter(SyncQueueItemModelAdapter());
    registerAdapter(TodoModelAdapter());
    registerAdapter(UserProfileModelAdapter());
  }
}
